name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # 1. Instala as dependências da raiz (onde está o Playwright)
    - name: Install Root dependencies
      run: yarn install 

    # 2. IMPORTANTE: Instala as dependências da API
    - name: Install API dependencies
      run: cd apps/api && yarn install

    # 3. IMPORTANTE: Instala as dependências do Web
    - name: Install Web dependencies
      run: cd apps/web && yarn install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # DEBUG: Adicione isso se o erro de "cd" continuar para vermos o que o robô vê
    - name: List files for debug
      run: ls -R

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30